name: Dev Testing

on:
  pull_request:
    branches:
    - main

jobs:
  build_and_testing:
    name: build and testing
    runs-on: ubuntu-latest
    environment: dev-testing
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create .env file
        run: |
          echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT  }}" > .env
          echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY  }}" >> .env
          echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY  }}" >> .env
          
      - name: Run app using docker compose
        run: |
          sudo docker compose up --build --detach pacmusic-dev
          
      - name: Hit endpoint
        run: |
          sleep 10
          curl http://localhost:5000
